resolver: lts-11.16
packages:
  - .
extra-deps:
  - digestive-functors-0.8.3.0
  - digestive-functors-heist-0.8.8.0
  - digestive-functors-snap-0.7.0.0
  - persistent-2.7.3.1
  - persistent-postgresql-2.6.3
  - snap-1.0.0.2
  - snap-extras-0.12.1.1
  - snaplet-persistent-0.6.0
