resolver: lts-14.27
packages:
  - .
extra-deps:
  - digestive-functors-0.8.4.2
  - digestive-functors-heist-0.8.8.1
  - digestive-functors-snap-0.7.0.1
  - heist-1.1.0.1
  - jmacro-0.6.17
  - lift-type-0.1.0.1
  - map-syntax-0.3
  - persistent-2.13.3.5
  - persistent-postgresql-2.13.5.0
  - pwstore-fast-2.4.4
  - restful-snap-0.4.2
  - snap-1.1.3.1
  - snap-extras-0.12.3.0
  - snaplet-persistent-0.7.1
  - xmlhtml-0.2.5.2
